// AnchoShared.idl : IDL source for AnchoShared
//

// This file will be processed by the MIDL tool to
// produce the type library (AnchoShared.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(02AA859B-5A1D-4723-90A9-89FEA90D1860),
	version(1.0),
	helpstring("AnchoShared 1.0 Type Library")
]
library AnchoSharedLib
{
	importlib("stdole2.tlb");
};
